### ISSUE TITLE
CURRENT TODO

### ISSUE THREAD

**Issue by Rinzii** [Rinzii/mim#2]
This is an active ongoing issue to track current objectives of the project. It will likely change a ton as I continue to work.

TODO:

- [ ] Finish development of specialized floating point vectors 2-4.
- [ ] Finish development of specialized floating point matrices 2x2-4x4.
- [ ] Implement a C style api inside of math.hpp that properly integrates with all of our custom data types.
- [ ] Perform finishing touches on float16.
- [ ] Implement Quaternions. Our quats should be floating point values and we won't implement any generic types for them.
- [ ] Fix cmake and make it not garbage. (Our current implementation of cmake is pretty bad. We should improve it sometime soon)

NICE TO HAVES: (Much later things)

- [ ] Implement SIMD variants for all of our data types. 
- [ ] Implement PCG random number generator [https://www.pcg-random.org/index.html] (A quality random number generator would be pretty useful for game mathe operations so i'd prob be worth to implement.
- [ ] Implement perlin and simplex noise generation. (They are used pretty often and would be nice to implement into the lib)
- [ ] Implement a point specialization for screen resolutions using int32_t.
- [ ] Implement a color specialization for handling color formats.
